<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVIZmxiK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVIZmxiK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVIZmxiK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVIZmxiK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVIZmxiK\App_KernelDevDebugContainer([
    'container.build_hash' => 'VIZmxiK',
    'container.build_id' => '27199de1',
    'container.build_time' => 1586249569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVIZmxiK');
